// Per-industry template configuration: copy, services, icons, colors, CTAs.
// {city} in strings is replaced with the lead's city (e.g. "Austin").
// Every industry needs: label, tag, colors, heroImage, hero, trust[3],
// services[6], why, stats fallback, reviews[3], contact, and CTA wording.

const industries = {
  handyman: {
    label: "Handyman Services",
    tag: "Handyman",
    colors: { primary: "#E8590C", primaryDark: "#C2410C", secondary: "#F97316" },
    heroImage: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=1920&q=80",
    hero: {
      title: "Your Trusted Handyman in {city}",
      subtitle: "Repairs, installs, and honey-do lists — done right the first time by a local pro.",
      ctaPrimary: "Call for a Free Estimate",
      ctaSecondary: "See Our Services",
    },
    trust: ["Licensed & Insured", "Free Estimates", "Serving the {city} Area"],
    servicesIntro: "One call covers your whole to-do list",
    services: [
      { icon: "fa-hammer", name: "Home Repairs", desc: "From squeaky doors to broken fixtures — fast fixes that hold up." },
      { icon: "fa-paint-roller", name: "Painting", desc: "Interior and exterior painting with clean lines and cleaner job sites." },
      { icon: "fa-faucet", name: "Plumbing Repairs", desc: "Leaky faucets, running toilets, and fixture swaps handled same-week." },
      { icon: "fa-bolt", name: "Electrical Work", desc: "Ceiling fans, outlets, and lighting installed safely and up to code." },
      { icon: "fa-ruler-combined", name: "Carpentry", desc: "Custom shelving, trim, decks, and repairs built to last." },
      { icon: "fa-trowel", name: "Drywall & Patching", desc: "Holes, cracks, and texture matched so you'd never know it happened." },
    ],
    why: {
      heading: "The Reliable Choice for {city} Homeowners",
      text: "No job too small, no surprises on the invoice. We show up when we say we will and stand behind every repair.",
      features: [
        { icon: "fa-bolt", title: "Fast Response", desc: "Quick scheduling and same-week service for most jobs" },
        { icon: "fa-shield-alt", title: "Guaranteed Work", desc: "Every job backed by our satisfaction guarantee" },
        { icon: "fa-tag", title: "Up-Front Pricing", desc: "Clear quotes before work starts — no hidden fees" },
      ],
    },
    fallbackStats: [
      { icon: "fa-house-chimney", label: "Locally Owned & Operated" },
      { icon: "fa-clipboard-check", label: "Free Estimates" },
      { icon: "fa-thumbs-up", label: "Satisfaction Guaranteed" },
    ],
    reviews: [
      "Fixed everything on my list in one visit and left the place spotless. Fair price, great communication.",
      "Showed up on time, quoted before starting, and the work was excellent. Finally a handyman I can rely on.",
      "Repaired our drywall and hung new fixtures — you can't even tell where the damage was. Highly recommend.",
    ],
    contact: { heading: "Ready to Knock Out That To-Do List?", cta: "Call Now for a Free Estimate" },
    footerTagline: "Your trusted local handyman in {city}, TX.",
  },

  barber: {
    label: "Barbershop",
    tag: "Barbershop",
    colors: { primary: "#3E2723", primaryDark: "#261612", secondary: "#795548" },
    heroImage: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=1920&q=80",
    hero: {
      title: "Sharp Cuts. No Shortcuts.",
      subtitle: "Precision fades, clean lineups, and classic cuts from {city} barbers who take their craft seriously.",
      ctaPrimary: "Call to Book a Chair",
      ctaSecondary: "See Our Services",
    },
    trust: ["Walk-Ins Welcome", "Experienced Barbers", "{city} Neighborhood Shop"],
    servicesIntro: "Every service finished with attention to detail",
    services: [
      { icon: "fa-scissors", name: "Haircuts", desc: "Classic and modern cuts tailored to your style and hair type." },
      { icon: "fa-bolt", name: "Fades", desc: "Skin fades, tapers, and blends with crisp, clean transitions." },
      { icon: "fa-ruler", name: "Lineups", desc: "Sharp edges and clean hairlines that keep you fresh between cuts." },
      { icon: "fa-user", name: "Beard Trims", desc: "Shaping, detailing, and hot-towel finishing for a polished look." },
      { icon: "fa-wand-magic-sparkles", name: "Straight-Razor Shaves", desc: "The classic hot-lather shave experience, done right." },
      { icon: "fa-child", name: "Kids Cuts", desc: "Patient barbers who make first haircuts easy — and cool." },
    ],
    why: {
      heading: "More Than a Haircut",
      text: "A good barbershop is part skill, part atmosphere. Sit down, relax, and walk out looking your best — every single time.",
      features: [
        { icon: "fa-scissors", title: "Craft First", desc: "Barbers who train on their technique and take pride in every chair" },
        { icon: "fa-clock", title: "Respect for Your Time", desc: "Quick turnarounds without ever rushing the cut" },
        { icon: "fa-handshake", title: "Neighborhood Vibe", desc: "A shop where they know your name and your usual" },
      ],
    },
    fallbackStats: [
      { icon: "fa-store", label: "Locally Owned Shop" },
      { icon: "fa-scissors", label: "Skilled Barbers" },
      { icon: "fa-users", label: "All Ages Welcome" },
    ],
    reviews: [
      "Best fade I've had in years. They took their time and the lineup was razor sharp.",
      "Great atmosphere, zero attitude, and my kid actually enjoys getting his hair cut now.",
      "Walked in on a Saturday, was in the chair fast, and walked out looking clean. This is my shop now.",
    ],
    contact: { heading: "Ready for a Fresh Cut?", cta: "Call to Book Your Cut" },
    footerTagline: "Sharp cuts and good conversation in {city}, TX.",
  },

  salon: {
    label: "Hair Salon",
    tag: "Hair Salon",
    colors: { primary: "#8E4585", primaryDark: "#6D3368", secondary: "#B06AA5" },
    heroImage: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1920&q=80",
    hero: {
      title: "Hair That Feels Like You",
      subtitle: "Cuts, color, and styling from {city} stylists who listen first and create looks you'll love living in.",
      ctaPrimary: "Call to Book an Appointment",
      ctaSecondary: "See Our Services",
    },
    trust: ["Experienced Stylists", "Consultations Included", "{city} Local Salon"],
    servicesIntro: "From subtle refresh to total transformation",
    services: [
      { icon: "fa-scissors", name: "Cuts & Styling", desc: "Precision cuts shaped to your face, lifestyle, and hair texture." },
      { icon: "fa-palette", name: "Color", desc: "Dimensional color, balayage, and gray coverage that looks natural." },
      { icon: "fa-star", name: "Highlights", desc: "Hand-painted brightness placed exactly where it flatters most." },
      { icon: "fa-spa", name: "Treatments", desc: "Deep conditioning and repair treatments for healthier hair." },
      { icon: "fa-wind", name: "Blowouts", desc: "Salon-smooth finish for events or just because." },
      { icon: "fa-gem", name: "Special Occasions", desc: "Updos and event styling that hold up from photos to last dance." },
    ],
    why: {
      heading: "A Salon Experience Worth Keeping",
      text: "Great hair starts with a stylist who actually listens. Every appointment begins with a real consultation — your goals, your maintenance level, your look.",
      features: [
        { icon: "fa-comments", title: "Consultation First", desc: "We talk before we touch a single strand" },
        { icon: "fa-award", title: "Skilled Stylists", desc: "Ongoing training in current techniques and trends" },
        { icon: "fa-heart", title: "Healthy Hair Focus", desc: "Products and methods that protect your hair long-term" },
      ],
    },
    fallbackStats: [
      { icon: "fa-store", label: "Locally Owned Salon" },
      { icon: "fa-award", label: "Experienced Stylists" },
      { icon: "fa-calendar-check", label: "Easy Scheduling" },
    ],
    reviews: [
      "My stylist listened to exactly what I wanted and the color came out better than the inspiration photo.",
      "Finally found a salon that doesn't rush. My cut grows out beautifully every time.",
      "The blowout lasted for days. Booking again before I even left the chair.",
    ],
    contact: { heading: "Ready for a New Look?", cta: "Call to Book an Appointment" },
    footerTagline: "Beautiful, healthy hair in {city}, TX.",
  },

  nails: {
    label: "Nail Salon & Spa",
    tag: "Nails & Spa",
    colors: { primary: "#C2185B", primaryDark: "#981247", secondary: "#E91E63" },
    heroImage: "https://images.unsplash.com/photo-1604654894610-df63bc536371?w=1920&q=80",
    hero: {
      title: "Nails Done Beautifully",
      subtitle: "Manicures, pedicures, and nail art in a clean, relaxing {city} studio that treats every set like a canvas.",
      ctaPrimary: "Call to Book an Appointment",
      ctaSecondary: "See Our Services",
    },
    trust: ["Sanitized Tools Every Client", "Relaxing Atmosphere", "{city} Local Studio"],
    servicesIntro: "Clean, careful, and always on trend",
    services: [
      { icon: "fa-hand-sparkles", name: "Manicures", desc: "Classic, gel, and dip manicures with a flawless finish." },
      { icon: "fa-spa", name: "Pedicures", desc: "Spa pedicures with massage — relaxation included." },
      { icon: "fa-gem", name: "Gel & Dip Powder", desc: "Long-lasting color that stays chip-free for weeks." },
      { icon: "fa-paintbrush", name: "Nail Art", desc: "From subtle accents to full custom designs." },
      { icon: "fa-hand", name: "Acrylics & Extensions", desc: "Natural-looking length and shape, applied with care." },
      { icon: "fa-leaf", name: "Spa Add-Ons", desc: "Paraffin, callus care, and massage upgrades for the full treat." },
    ],
    why: {
      heading: "Where Clean Meets Beautiful",
      text: "Fresh tools for every client, unhurried appointments, and techs who care about nail health — not just the polish on top.",
      features: [
        { icon: "fa-shield-virus", title: "Hygiene First", desc: "Hospital-grade sterilization for every service" },
        { icon: "fa-clock", title: "Never Rushed", desc: "Your appointment time is yours — we don't double-book" },
        { icon: "fa-heart", title: "Nail Health", desc: "Techniques and products that keep natural nails strong" },
      ],
    },
    fallbackStats: [
      { icon: "fa-store", label: "Locally Owned Studio" },
      { icon: "fa-shield-virus", label: "Sanitized Every Service" },
      { icon: "fa-calendar-check", label: "Walk-Ins Welcome" },
    ],
    reviews: [
      "The cleanest nail salon I've been to, and my gel set lasted almost four weeks without a chip.",
      "They never rush and the attention to detail on my nail art was incredible.",
      "The spa pedicure is my monthly reset. Friendly staff and so relaxing.",
    ],
    contact: { heading: "Treat Yourself — You've Earned It", cta: "Call to Book an Appointment" },
    footerTagline: "Beautiful nails and a relaxing escape in {city}, TX.",
  },

  massage: {
    label: "Massage Therapy",
    tag: "Massage",
    colors: { primary: "#5B7B6A", primaryDark: "#446053", secondary: "#7C9E8C" },
    heroImage: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1920&q=80",
    hero: {
      title: "Relief You Can Feel",
      subtitle: "Therapeutic massage in {city} focused on real results — less pain, less stress, better movement.",
      ctaPrimary: "Call to Book a Session",
      ctaSecondary: "See Our Services",
    },
    trust: ["Licensed Therapists", "Customized Sessions", "{city} Local Studio"],
    servicesIntro: "Every session tailored to what your body needs",
    services: [
      { icon: "fa-spa", name: "Swedish Massage", desc: "Full-body relaxation that melts away stress and tension." },
      { icon: "fa-hand-fist", name: "Deep Tissue", desc: "Focused pressure to release chronic knots and tight muscles." },
      { icon: "fa-person-running", name: "Sports Massage", desc: "Recovery and performance work for active bodies." },
      { icon: "fa-crosshairs", name: "Trigger Point", desc: "Targeted relief for stubborn pain patterns and headaches." },
      { icon: "fa-fire", name: "Hot Stone", desc: "Heated stones that ease muscles into deep relaxation." },
      { icon: "fa-person-pregnant", name: "Prenatal Massage", desc: "Safe, comfortable relief through every trimester." },
    ],
    why: {
      heading: "Massage With a Purpose",
      text: "Every body is different. Your session starts with a conversation about where you hurt and how you want to feel — then we work toward it.",
      features: [
        { icon: "fa-user-doctor", title: "Licensed & Trained", desc: "Certified therapists with clinical technique" },
        { icon: "fa-sliders", title: "Customized Pressure", desc: "From feather-light to deep — always your call" },
        { icon: "fa-calendar-check", title: "Easy Booking", desc: "Appointments that fit your schedule, including evenings" },
      ],
    },
    fallbackStats: [
      { icon: "fa-certificate", label: "Licensed Therapists" },
      { icon: "fa-spa", label: "Calm, Private Studio" },
      { icon: "fa-heart", label: "Results-Focused Care" },
    ],
    reviews: [
      "I came in with terrible neck pain and walked out feeling like a new person. Incredibly skilled hands.",
      "The therapist actually listened to what I needed instead of a one-size-fits-all routine.",
      "Best deep tissue massage I've found in the area. My back has never felt better.",
    ],
    contact: { heading: "Your Body Will Thank You", cta: "Call to Book a Session" },
    footerTagline: "Therapeutic massage and real relief in {city}, TX.",
  },

  cleaning: {
    label: "Cleaning Services",
    tag: "House Cleaning",
    colors: { primary: "#0F7BB8", primaryDark: "#0B5E8D", secondary: "#38A3DC" },
    heroImage: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1920&q=80",
    hero: {
      title: "Come Home to Clean",
      subtitle: "Reliable, detail-obsessed house cleaning for {city} homes — the same great clean, every visit.",
      ctaPrimary: "Call for a Free Quote",
      ctaSecondary: "See Our Services",
    },
    trust: ["Background-Checked Cleaners", "Supplies Included", "Serving the {city} Area"],
    servicesIntro: "From weekly upkeep to top-to-bottom deep cleans",
    services: [
      { icon: "fa-house", name: "Recurring Cleaning", desc: "Weekly, bi-weekly, or monthly visits that keep your home guest-ready." },
      { icon: "fa-broom", name: "Deep Cleaning", desc: "Baseboards, blinds, behind appliances — the works." },
      { icon: "fa-box-open", name: "Move-In / Move-Out", desc: "Empty-home cleans that help you get the deposit back." },
      { icon: "fa-building", name: "Office Cleaning", desc: "Professional cleaning for small offices and commercial spaces." },
      { icon: "fa-spray-can-sparkles", name: "Kitchen & Bath Detail", desc: "The rooms that matter most, scrubbed to shine." },
      { icon: "fa-couch", name: "Add-On Services", desc: "Interior windows, oven, fridge, and laundry on request." },
    ],
    why: {
      heading: "Cleaning You Don't Have to Think About",
      text: "Same trusted cleaners, a consistent checklist, and a satisfaction guarantee. If something's not right, we come back and fix it — free.",
      features: [
        { icon: "fa-user-check", title: "Vetted & Trusted", desc: "Background-checked, trained, and insured cleaners" },
        { icon: "fa-list-check", title: "Consistent Checklist", desc: "The same thorough clean documented on every visit" },
        { icon: "fa-rotate-left", title: "Re-Clean Guarantee", desc: "Not happy with a spot? We'll return within 24 hours" },
      ],
    },
    fallbackStats: [
      { icon: "fa-house-circle-check", label: "Locally Owned & Operated" },
      { icon: "fa-pump-soap", label: "Supplies Included" },
      { icon: "fa-thumbs-up", label: "Satisfaction Guaranteed" },
    ],
    reviews: [
      "My house has never looked this good. They hit every detail, even the spots I forgot existed.",
      "Same wonderful team every visit and the checklist means nothing gets skipped.",
      "Booked a move-out clean and got my full deposit back. Worth every penny.",
    ],
    contact: { heading: "Ready for a Spotless Home?", cta: "Call for a Free Quote" },
    footerTagline: "Trusted home cleaning across {city}, TX.",
  },

  "dry-cleaning": {
    label: "Dry Cleaners",
    tag: "Dry Cleaning",
    colors: { primary: "#00796B", primaryDark: "#00594F", secondary: "#26A69A" },
    heroImage: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=1920&q=80",
    hero: {
      title: "Crisp, Clean, Ready to Wear",
      subtitle: "Expert dry cleaning, laundry, and alterations in {city} — with the fast turnaround your week depends on.",
      ctaPrimary: "Call for Hours & Pricing",
      ctaSecondary: "See Our Services",
    },
    trust: ["Fast Turnaround", "Care for Delicate Fabrics", "{city} Neighborhood Cleaners"],
    servicesIntro: "Professional care for everything in your closet",
    services: [
      { icon: "fa-shirt", name: "Dry Cleaning", desc: "Suits, dresses, and delicates cleaned and pressed to perfection." },
      { icon: "fa-jug-detergent", name: "Wash & Fold", desc: "Drop off your laundry, pick it up fresh and folded." },
      { icon: "fa-user-tie", name: "Shirt Service", desc: "Crisp, professionally pressed shirts ready for the week." },
      { icon: "fa-scissors", name: "Alterations", desc: "Hems, takes, and repairs done with tailor-level care." },
      { icon: "fa-ring", name: "Wedding & Formal", desc: "Gown cleaning and preservation for your most important pieces." },
      { icon: "fa-couch", name: "Household Items", desc: "Comforters, drapes, and linens cleaned and refreshed." },
    ],
    why: {
      heading: "The Cleaners Your Wardrobe Deserves",
      text: "From everyday shirts to once-in-a-lifetime gowns, every garment gets inspected, treated, and finished by people who know fabric.",
      features: [
        { icon: "fa-magnifying-glass", title: "Garment Inspection", desc: "Stains and loose buttons caught before cleaning" },
        { icon: "fa-clock", title: "Reliable Turnaround", desc: "In by morning, ready when promised" },
        { icon: "fa-hand-holding-heart", title: "Delicate Care", desc: "Gentle processes for silk, wool, and specialty fabrics" },
      ],
    },
    fallbackStats: [
      { icon: "fa-store", label: "Locally Owned Cleaners" },
      { icon: "fa-clock", label: "Fast Turnaround" },
      { icon: "fa-shirt", label: "All Fabrics Welcome" },
    ],
    reviews: [
      "They got a stain out that two other cleaners gave up on. My go-to from now on.",
      "Always ready when promised and my shirts come back perfectly pressed.",
      "Had a suit altered and dry cleaned here — fits better than when I bought it.",
    ],
    contact: { heading: "Drop Off Today, Fresh Tomorrow", cta: "Call for Hours & Pricing" },
    footerTagline: "Quality garment care in {city}, TX.",
  },

  auto: {
    label: "Auto Repair",
    tag: "Auto Repair",
    colors: { primary: "#C62828", primaryDark: "#9C1F1F", secondary: "#E53935" },
    heroImage: "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=1920&q=80",
    hero: {
      title: "Honest Auto Repair in {city}",
      subtitle: "Straight answers, fair prices, and repairs done right — from mechanics who explain before they fix.",
      ctaPrimary: "Call to Schedule Service",
      ctaSecondary: "See Our Services",
    },
    trust: ["ASE-Style Expertise", "Up-Front Estimates", "Serving the {city} Area"],
    servicesIntro: "Full-service care for every make and model",
    services: [
      { icon: "fa-oil-can", name: "Oil Changes", desc: "Quick, clean oil service with a multi-point inspection included." },
      { icon: "fa-car-burst", name: "Brakes", desc: "Pads, rotors, and full brake system service you can trust your family to." },
      { icon: "fa-laptop-code", name: "Diagnostics", desc: "Check engine light on? We find the real cause, not just the code." },
      { icon: "fa-gears", name: "Engine & Transmission", desc: "Major repairs handled with quality parts and clear communication." },
      { icon: "fa-car-battery", name: "Batteries & Electrical", desc: "Testing, replacement, and electrical gremlins tracked down." },
      { icon: "fa-calendar-check", name: "Scheduled Maintenance", desc: "Factory-recommended service that protects your warranty." },
    ],
    why: {
      heading: "A Shop That Talks Straight",
      text: "No scare tactics, no mystery line items. We show you what's wrong, tell you what it costs, and fix only what you approve.",
      features: [
        { icon: "fa-file-invoice-dollar", title: "Estimates First", desc: "Written estimates and your approval before any work" },
        { icon: "fa-camera", title: "Show, Don't Tell", desc: "See the worn part before we replace it" },
        { icon: "fa-road", title: "Done-Right Guarantee", desc: "We stand behind our repairs, mile after mile" },
      ],
    },
    fallbackStats: [
      { icon: "fa-warehouse", label: "Locally Owned Shop" },
      { icon: "fa-file-invoice-dollar", label: "Up-Front Estimates" },
      { icon: "fa-wrench", label: "All Makes & Models" },
    ],
    reviews: [
      "They showed me the worn brake pads before replacing them and the final bill matched the quote exactly.",
      "Fixed what two other shops couldn't figure out, and charged less than either quoted.",
      "Honest mechanics are hard to find. This shop has earned all my future business.",
    ],
    contact: { heading: "Car Trouble? We've Got You", cta: "Call to Schedule Service" },
    footerTagline: "Honest auto repair for {city} drivers.",
  },

  electrician: {
    label: "Electrician",
    tag: "Electrician",
    colors: { primary: "#F59E0B", primaryDark: "#B45309", secondary: "#FBBF24" },
    heroImage: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=1920&q=80",
    hero: {
      title: "Licensed Electricians, On Time",
      subtitle: "Safe, code-compliant electrical work for {city} homes and businesses — from new outlets to full panel upgrades.",
      ctaPrimary: "Call for a Free Estimate",
      ctaSecondary: "See Our Services",
    },
    trust: ["Licensed & Insured", "Code-Compliant Work", "Serving the {city} Area"],
    servicesIntro: "Residential and commercial electrical, done safely",
    services: [
      { icon: "fa-screwdriver-wrench", name: "Electrical Repairs", desc: "Dead outlets, flickering lights, and tripping breakers fixed fast." },
      { icon: "fa-table-cells", name: "Panel Upgrades", desc: "Modern panels that safely handle today's electrical loads." },
      { icon: "fa-lightbulb", name: "Lighting Installation", desc: "Recessed, landscape, and smart lighting installed clean." },
      { icon: "fa-charging-station", name: "EV Charger Installation", desc: "Level 2 home charging installed to manufacturer spec." },
      { icon: "fa-house-signal", name: "Whole-Home Wiring", desc: "Rewiring, new circuits, and remodel electrical work." },
      { icon: "fa-clipboard-check", name: "Safety Inspections", desc: "Thorough inspections for older homes and home purchases." },
    ],
    why: {
      heading: "Electrical Work You Can Trust Behind Your Walls",
      text: "Electricity isn't a place to cut corners. Every job is permitted where required, built to code, and tested before we leave.",
      features: [
        { icon: "fa-certificate", title: "Licensed Pros", desc: "Trained, licensed electricians on every job" },
        { icon: "fa-shield-halved", title: "Safety First", desc: "Code-compliant work, tested and verified" },
        { icon: "fa-file-invoice-dollar", title: "Clear Pricing", desc: "Up-front quotes before the work begins" },
      ],
    },
    fallbackStats: [
      { icon: "fa-certificate", label: "Licensed & Insured" },
      { icon: "fa-bolt", label: "Residential & Commercial" },
      { icon: "fa-clipboard-check", label: "Free Estimates" },
    ],
    reviews: [
      "Diagnosed our breaker issue in minutes and had it fixed the same visit. Professional from start to finish.",
      "Installed our EV charger and took time to explain the whole setup. Clean work, fair price.",
      "Finally an electrician who shows up on time and leaves the work area cleaner than they found it.",
    ],
    contact: { heading: "Got an Electrical Project or Problem?", cta: "Call for a Free Estimate" },
    footerTagline: "Safe, professional electrical work in {city}, TX.",
  },

  landscaping: {
    label: "Landscaping",
    tag: "Landscaping",
    colors: { primary: "#2E7D32", primaryDark: "#1D5220", secondary: "#4CAF50" },
    heroImage: "https://images.unsplash.com/photo-1558904541-efa843a96f01?w=1920&q=80",
    hero: {
      title: "Your Yard, at Its Best",
      subtitle: "Design, installation, and reliable maintenance that make your {city} outdoor space the one neighbors notice.",
      ctaPrimary: "Call for a Free Quote",
      ctaSecondary: "See Our Services",
    },
    trust: ["Free Design Consults", "Reliable Crews", "Serving the {city} Area"],
    servicesIntro: "From weekly mowing to full outdoor transformations",
    services: [
      { icon: "fa-leaf", name: "Lawn Care", desc: "Mowing, edging, and fertilization on a schedule you can count on." },
      { icon: "fa-tree", name: "Tree & Shrub Care", desc: "Trimming and pruning that keep plants healthy and shaped." },
      { icon: "fa-droplet", name: "Irrigation", desc: "Sprinkler installation and repair that saves water and keeps grass green." },
      { icon: "fa-compass-drafting", name: "Landscape Design", desc: "Native, drought-smart designs built for Texas heat." },
      { icon: "fa-cubes-stacked", name: "Hardscaping", desc: "Patios, walkways, and retaining walls that add living space." },
      { icon: "fa-broom", name: "Cleanups & Mulching", desc: "Seasonal cleanups and fresh mulch that make beds pop." },
    ],
    why: {
      heading: "A Yard You're Proud to Come Home To",
      text: "We treat your property like our own — showing up on schedule, cleaning up completely, and building landscapes that thrive in Central Texas.",
      features: [
        { icon: "fa-calendar-check", title: "Dependable Schedule", desc: "Crews that arrive when promised, every time" },
        { icon: "fa-sun", title: "Texas-Tough Plants", desc: "Designs that survive the heat and look great doing it" },
        { icon: "fa-broom", title: "Spotless Cleanup", desc: "We haul away every clipping and leaf before we go" },
      ],
    },
    fallbackStats: [
      { icon: "fa-leaf", label: "Locally Owned & Operated" },
      { icon: "fa-clipboard-check", label: "Free Quotes" },
      { icon: "fa-calendar-check", label: "Reliable Scheduling" },
    ],
    reviews: [
      "Our yard went from embarrassing to the best on the block. The design work was outstanding.",
      "They show up every week like clockwork and the lawn has never looked healthier.",
      "Fixed our irrigation system and our water bill dropped the very next month.",
    ],
    contact: { heading: "Ready to Love Your Yard Again?", cta: "Call for a Free Quote" },
    footerTagline: "Beautiful, low-maintenance landscapes in {city}, TX.",
  },

  plumbing: {
    label: "Plumbing",
    tag: "Plumber",
    colors: { primary: "#1565C0", primaryDark: "#0E4686", secondary: "#1E88E5" },
    heroImage: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1920&q=80",
    hero: {
      title: "Plumbing Problems, Solved",
      subtitle: "Fast, clean, licensed plumbing for {city} homes — from dripping faucets to water heater replacements.",
      ctaPrimary: "Call for Service",
      ctaSecondary: "See Our Services",
    },
    trust: ["Licensed & Insured", "Up-Front Pricing", "Serving the {city} Area"],
    servicesIntro: "Repairs, replacements, and emergencies handled",
    services: [
      { icon: "fa-faucet-drip", name: "Leak Repair", desc: "Faucets, pipes, and hidden leaks found and fixed fast." },
      { icon: "fa-fire-flame-simple", name: "Water Heaters", desc: "Repair and replacement — tank and tankless." },
      { icon: "fa-toilet", name: "Toilets & Fixtures", desc: "Repairs and upgrades installed clean and leak-free." },
      { icon: "fa-water", name: "Drain Cleaning", desc: "Slow or clogged drains cleared the right way." },
      { icon: "fa-house-flood-water", name: "Sewer & Main Lines", desc: "Camera inspections and line repairs without guesswork." },
      { icon: "fa-gauge-high", name: "Water Pressure", desc: "Pressure problems diagnosed and corrected." },
    ],
    why: {
      heading: "The Plumber {city} Recommends",
      text: "We quote before we work, protect your home while we're in it, and leave everything cleaner than we found it.",
      features: [
        { icon: "fa-file-invoice-dollar", title: "Price Before Work", desc: "Approved up-front — no surprise invoices" },
        { icon: "fa-shoe-prints", title: "Respect for Your Home", desc: "Shoe covers, drop cloths, full cleanup" },
        { icon: "fa-bolt", title: "Fast Response", desc: "Same-day service for urgent problems" },
      ],
    },
    fallbackStats: [
      { icon: "fa-certificate", label: "Licensed & Insured" },
      { icon: "fa-file-invoice-dollar", label: "Up-Front Pricing" },
      { icon: "fa-bolt", label: "Fast Response" },
    ],
    reviews: [
      "Fixed our water heater the same day we called. Professional, clean, and fairly priced.",
      "Quoted a price, stuck to it, and the work was flawless. Rare these days.",
      "Cleared a stubborn drain other plumbers couldn't. Highly recommend.",
    ],
    contact: { heading: "Got a Plumbing Problem?", cta: "Call Now for Service" },
    footerTagline: "Licensed, reliable plumbing in {city}, TX.",
  },

  hvac: {
    label: "Heating & Air",
    tag: "HVAC",
    colors: { primary: "#0277BD", primaryDark: "#01579B", secondary: "#F57C00" },
    heroImage: "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=1920&q=80",
    hero: {
      title: "Comfort, All Year Long",
      subtitle: "AC repair, heating service, and new system installs that keep {city} homes comfortable through every season.",
      ctaPrimary: "Call for Service",
      ctaSecondary: "See Our Services",
    },
    trust: ["Licensed & Insured", "All Brands Serviced", "Serving the {city} Area"],
    servicesIntro: "Keeping Texas homes cool when it counts",
    services: [
      { icon: "fa-snowflake", name: "AC Repair", desc: "Fast diagnosis and repair when the Texas heat won't wait." },
      { icon: "fa-temperature-arrow-up", name: "Heating Service", desc: "Furnace and heat pump repair for chilly nights." },
      { icon: "fa-arrows-rotate", name: "System Replacement", desc: "Right-sized, efficient systems installed properly." },
      { icon: "fa-calendar-check", name: "Maintenance Plans", desc: "Seasonal tune-ups that prevent breakdowns and cut bills." },
      { icon: "fa-wind", name: "Ductwork", desc: "Duct sealing and repair for even cooling in every room." },
      { icon: "fa-house-signal", name: "Smart Thermostats", desc: "Installation and setup for smarter energy use." },
    ],
    why: {
      heading: "The Comfort Team {city} Counts On",
      text: "When your AC dies in August, you need someone who answers the phone, shows up fast, and fixes it right. That's the standard we run on.",
      features: [
        { icon: "fa-bolt", title: "Fast Response", desc: "Priority scheduling when systems are down" },
        { icon: "fa-file-invoice-dollar", title: "Honest Options", desc: "Repair vs. replace laid out clearly, your choice" },
        { icon: "fa-certificate", title: "Trained Techs", desc: "Licensed, certified, and background-checked" },
      ],
    },
    fallbackStats: [
      { icon: "fa-certificate", label: "Licensed & Insured" },
      { icon: "fa-snowflake", label: "All Brands Serviced" },
      { icon: "fa-bolt", label: "Fast Response" },
    ],
    reviews: [
      "AC went out on a 100-degree day and they had us cool again by evening. Lifesavers.",
      "Gave us a straight answer on repair vs. replace with real numbers. No pressure at all.",
      "The maintenance plan already paid for itself — they caught a failing part before summer.",
    ],
    contact: { heading: "Too Hot? Too Cold? Call Us", cta: "Call Now for Service" },
    footerTagline: "Reliable heating and cooling in {city}, TX.",
  },

  "pressure-washing": {
    label: "Pressure Washing",
    tag: "Pressure Washing",
    colors: { primary: "#0097A7", primaryDark: "#006D79", secondary: "#00BCD4" },
    heroImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80",
    hero: {
      title: "Like New, Without the New Price",
      subtitle: "Professional pressure washing that brings {city} driveways, siding, and patios back to life.",
      ctaPrimary: "Call for a Free Quote",
      ctaSecondary: "See Our Services",
    },
    trust: ["Surface-Safe Methods", "Fully Insured", "Serving the {city} Area"],
    servicesIntro: "The right pressure for every surface",
    services: [
      { icon: "fa-road", name: "Driveways & Sidewalks", desc: "Oil stains, tire marks, and years of grime — gone." },
      { icon: "fa-house", name: "House Washing", desc: "Gentle soft-wash for siding, stucco, and brick." },
      { icon: "fa-umbrella-beach", name: "Patios & Decks", desc: "Outdoor living spaces cleaned and ready for company." },
      { icon: "fa-border-all", name: "Fences", desc: "Wood and vinyl fences restored to their original color." },
      { icon: "fa-house-chimney-window", name: "Roof Cleaning", desc: "Safe, low-pressure removal of streaks and buildup." },
      { icon: "fa-building", name: "Commercial", desc: "Storefronts and lots that make the right first impression." },
    ],
    why: {
      heading: "Curb Appeal, Restored in an Afternoon",
      text: "The right equipment, the right detergents, and the right pressure for each surface — powerful on grime, gentle on your property.",
      features: [
        { icon: "fa-shield-halved", title: "Surface-Safe", desc: "Soft-wash methods that never damage siding or shingles" },
        { icon: "fa-droplet", title: "Pro Equipment", desc: "Commercial-grade results a rental unit can't match" },
        { icon: "fa-images", title: "Before & After Proof", desc: "See the difference documented on every job" },
      ],
    },
    fallbackStats: [
      { icon: "fa-house-circle-check", label: "Locally Owned & Operated" },
      { icon: "fa-clipboard-check", label: "Free Quotes" },
      { icon: "fa-shield-halved", label: "Fully Insured" },
    ],
    reviews: [
      "Our driveway looks brand new. I didn't think those stains would ever come out.",
      "They soft-washed the whole house and the siding looks freshly painted.",
      "Fast, careful, and the before-and-after photos were unreal. Booking yearly now.",
    ],
    contact: { heading: "Ready to See the Difference?", cta: "Call for a Free Quote" },
    footerTagline: "Restoring curb appeal across {city}, TX.",
  },

  painting: {
    label: "Painting",
    tag: "Painter",
    colors: { primary: "#6A1B9A", primaryDark: "#4E1372", secondary: "#8E24AA" },
    heroImage: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=1920&q=80",
    hero: {
      title: "Fresh Paint, Flawless Finish",
      subtitle: "Interior and exterior painting for {city} homes — clean lines, quality paint, and a crew that respects your space.",
      ctaPrimary: "Call for a Free Estimate",
      ctaSecondary: "See Our Services",
    },
    trust: ["Detailed Prep Work", "Quality Paints", "Serving the {city} Area"],
    servicesIntro: "Prep-obsessed painting that lasts",
    services: [
      { icon: "fa-paint-roller", name: "Interior Painting", desc: "Walls, ceilings, and trim with crisp, clean edges." },
      { icon: "fa-house", name: "Exterior Painting", desc: "Weather-resistant finishes that protect and impress." },
      { icon: "fa-door-open", name: "Cabinets & Doors", desc: "Factory-smooth refinishing that transforms kitchens." },
      { icon: "fa-trowel", name: "Drywall & Texture", desc: "Repairs and texture matching before the first coat." },
      { icon: "fa-swatchbook", name: "Color Consultation", desc: "Help choosing colors you'll still love in five years." },
      { icon: "fa-building", name: "Commercial Painting", desc: "Offices and storefronts painted around your schedule." },
    ],
    why: {
      heading: "It's All in the Prep",
      text: "Great paint jobs are 80% preparation. We patch, sand, prime, and mask properly — so the finish looks perfect and stays that way.",
      features: [
        { icon: "fa-tape", title: "Meticulous Prep", desc: "Surfaces repaired and primed before any color goes on" },
        { icon: "fa-broom", title: "Clean Job Sites", desc: "Furniture protected, floors covered, daily cleanup" },
        { icon: "fa-award", title: "Quality Materials", desc: "Premium paints that cover better and last longer" },
      ],
    },
    fallbackStats: [
      { icon: "fa-paint-roller", label: "Locally Owned & Operated" },
      { icon: "fa-clipboard-check", label: "Free Estimates" },
      { icon: "fa-award", label: "Quality Guaranteed" },
    ],
    reviews: [
      "The lines are so crisp it looks computer-generated. Best paint crew we've hired.",
      "They finished on schedule and you'd never know they were here — except the house looks amazing.",
      "Our cabinets look factory-new. Should have done this years ago.",
    ],
    contact: { heading: "Ready for a Fresh Look?", cta: "Call for a Free Estimate" },
    footerTagline: "Beautiful, lasting paintwork in {city}, TX.",
  },

  generic: {
    label: "Local Services",
    tag: "Local Business",
    colors: { primary: "#E94560", primaryDark: "#C22E47", secondary: "#FF6B81" },
    heroImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&q=80",
    hero: {
      title: "Proudly Serving {city}",
      subtitle: "Quality service, fair prices, and the personal touch only a local business can offer.",
      ctaPrimary: "Call Us Today",
      ctaSecondary: "See Our Services",
    },
    trust: ["Locally Owned", "Customer-First Service", "Serving the {city} Area"],
    servicesIntro: "Here's how we can help",
    services: [
      { icon: "fa-star", name: "Quality Service", desc: "Skilled work delivered with pride and attention to detail." },
      { icon: "fa-bolt", name: "Fast Turnaround", desc: "Responsive scheduling that respects your time." },
      { icon: "fa-tag", name: "Fair Pricing", desc: "Honest, transparent pricing with no surprises." },
      { icon: "fa-handshake", name: "Personal Attention", desc: "Talk to the people who actually do the work." },
      { icon: "fa-thumbs-up", name: "Satisfaction Focused", desc: "We're not done until you're happy with the result." },
      { icon: "fa-location-dot", name: "Truly Local", desc: "Your neighbors, invested in this community." },
    ],
    why: {
      heading: "Why {city} Chooses Local",
      text: "When you work with a local business, you get accountability, care, and someone who answers the phone. That's us.",
      features: [
        { icon: "fa-handshake", title: "Personal Service", desc: "Work directly with the owner, not a call center" },
        { icon: "fa-bolt", title: "Responsive", desc: "Quick answers and flexible scheduling" },
        { icon: "fa-heart", title: "Community First", desc: "Proudly serving our neighbors" },
      ],
    },
    fallbackStats: [
      { icon: "fa-store", label: "Locally Owned & Operated" },
      { icon: "fa-handshake", label: "Personal Service" },
      { icon: "fa-thumbs-up", label: "Satisfaction Guaranteed" },
    ],
    reviews: [
      "Wonderful local business — friendly, professional, and they truly care about their customers.",
      "Great experience from start to finish. You can tell they take pride in what they do.",
      "Responsive, fair, and high quality. Exactly what you hope for from a local company.",
    ],
    contact: { heading: "Ready to Get Started?", cta: "Call Us Today" },
    footerTagline: "Proudly serving {city}, TX.",
  },
};

module.exports = industries;
